### ISSUE TITLE
I Found some Grammar mistakes in docs

### ISSUE THREAD

**Issue by MohamedMafaz** [appwrite/playground-for-web#75]
### 💭 Description

Please assign me this issue, I'll fix it

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
We love contributions, but we suggest you try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel. I'm going to close this to avoid extra attention during hacktoberfest.
