### ISSUE TITLE
Logo is not appearing

### ISSUE THREAD

**Issue by amanr-dev** [appwrite/playground-for-web#99]
The playground logo does not appear.

Screenshot:
![Screenshot 2024-02-14 111043](https://github.com/appwrite/playground-for-web/assets/124811276/f110d3c4-96e2-40ce-a767-4e0d30b17b2e)

**Comment by EVDOG4LIFE** [comment]
Thanks for submitting, I've confirmed this running on gitpod. Looks like the `appwrite-white.svg` is linking to a dead url.

**Comment by TomoyaKuroda** [comment]
I made a pull request to fix this issue. #107
